---
weight: 1
title: "Introdução"
lang: "pt"
header-includes:   
  - \usepackage{amsmath}
  - \usepackage{amssymb}
  - \usepackage{amsthm}
  - \usepackage{bm}
  - \usepackage{bbm}
  - \usepackage{amsfonts}
  - \usepackage{mathtools}
   - \usepackage{tikz}
   - \usetikzlibrary{fit,shapes.geometric, arrows}
   - \usetikzlibrary{trees}
   - \usepackage{caption} 
   - \usepackage{hyperref} 
   - \usepackage[utf8]{inputenc}
   - \usepackage[portuguese]{babel} 
   - \usepackage[T1]{fontenc}
slug: cite-something
categories: []
tags: []
bibliography: [reference.bib]
link-citations: true
latex_engine: xelatex
---

\newtheorem{exemplo}{Exemplo}
\newtheorem{assumption}{Assumption}



A estatística consiste numa metodologia científica para obtenção, organização, redução, apresentação, análise e interpretação  de dados oriundos das mais variadas áreas das ciências experimentais, cujo objetivo principal é auxiliar a tomada de decisão em situações de incerteza, veja por exemplo @bussab e @barbetta2004. Informalmente, podemos definir a ciência estatística como um conjunto de técnicas utilizadas para estudar a condição de uma população usando informações obtidas a partir de dados observados.




#### De onde vêm os dados? ####
	
 
Dados são resultados de observações de algum fenômeno, podendo ser obtidos, para análise, a partir de observações espontâneas  ou por meio de realização de  experimentos planejados. 
 
 
 
 
 

- Dados oriundos de observações de fenômenos quaisquer: 
     - observar o desempenho natural de um novo equipamento.

	
Nesse caso, o desempenho natural do equipamento é  a característica que se deseja estudar.


 * Dados oriundos de experimentos planejados: 
 -  observar o desempenho  de um novo  equipamento, alterando de modo proposital alguma característica.

	Nesse caso, o interesse é estudar  o desempenho do equipamento levando em consideração a variação da característica alterada.



		
A estatística, muitas vezes, é de grande utilidade quando o método científico é utilizado  para testar teoria ou hipóteses em muitas áreas do conhecimento. Esse método pode ser resumido nos seguintes passos.

* Um problema é formulado em que, muitas vezes, uma hipótese precisa ser testada.

	* Para solucionar o problema, deve-se coletar informações que sejam relevantes, para isso pode-se formular um experimento. Em muitas áreas do conhecimento o planejamento do experimento não é simples, ou até mesmo não é possível, e uma estratégia pode ser a observação de algum fenômeno  de interesse.	
	
*	Os resultados do experimento podem ser utilizados para se obter conclusões, definitivas ou não.
*  Os passo 2 e 3 podem ser repetidos quantas vezes forem necessárias.





```{example}
Ao observar um equipamento que deveria estar operando, nota-se que este está parado.

- Hipotese: falta de energia elétrica.

- Faz-se a observação para verificar a hipótese

- Se não é falta de energia, outras observações e testes serão requeridos.

- Os passos serão executados até que se tenha uma conclusão, que pode ser definitiva ou não.
		
```

	
		

Muitas vezes, na aplicação do método científico a estatística é uma ferramenta  indispensável, podendo ser requerida em todas as etapas.


```{example}
	Ao observar um equipamento em operação, desconfia-se que este não está operando como deveria.

* Hipótese: o equipamento está desregulado, neste caso pode-se optar por realizar um processo de amostragem de produtos fabricados pela máquina, então faz-se necessário o planejamento de um experimento para coleta das amostras (área da estatística).

* Após o planejamento, o experimento é realizado e ferramentas da estatística podem ser aplicadas para obter alguma conclusão.

* Caso os resultados sejam inconclusivos, novos experimentos poderão ser realizados.

* Os passos podem ser executados até que se tenha uma conclusão.
```


